/**
 * PackWise AI - Structured Knowledge Base
 * Relational commodity profiles, food scientific reference properties,
 * and packaging material technical specifications.
 */

import { Commodity, PackagingMaterial } from '../../src/types/packwise.js';

export const COMMODITIES: Commodity[] = [
  {
    id: 1,
    name: 'Tomato',
    slug: 'tomato',
    category: 'Fresh Produce',
    perishability: 'HIGH',
    description: 'Solanaceous climacteric berry fruit. High water content, moderate to high respiration rate, sensitive to compressive bruising and chilling below 10°C.',
    sampleImageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80',
    properties: {
      commodityId: 1,
      typicalPhMin: 4.3,
      typicalPhMax: 4.9,
      moistureContentPct: 94.0,
      moistureSensitivity: 'HIGH',
      respirationRate: 'HIGH',
      mechanicalSensitivity: 'HIGH',
      chillingSensitivity: true,
      optimalTempMinC: 12.0,
      optimalTempMaxC: 15.0,
      optimalRhMinPct: 85,
      optimalRhMaxPct: 90,
      typicalShelfLifeDays: 10,
      ethyleneProduction: 'HIGH',
      keyDeteriorationFactors: 'Compression bruising, chilling injury, transpirational water loss, gray mold (Botrytis).',
      packagingRequirements: 'Ventilated corrugated master cartons with molded pulp or paper trays; avoid sealed hermetic bags to prevent anaerobic decay.'
    }
  },
  {
    id: 2,
    name: 'Potato',
    slug: 'potato',
    category: 'Root Vegetables',
    perishability: 'LOW',
    description: 'Starchy underground storage tuber. Low respiration once cured; highly sensitive to light-induced solanine greening and damp rotting.',
    sampleImageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&auto=format&fit=crop&q=80',
    properties: {
      commodityId: 2,
      typicalPhMin: 5.4,
      typicalPhMax: 6.0,
      moistureContentPct: 79.0,
      moistureSensitivity: 'MODERATE',
      respirationRate: 'VERY_LOW',
      mechanicalSensitivity: 'MODERATE',
      chillingSensitivity: false,
      optimalTempMinC: 7.0,
      optimalTempMaxC: 10.0,
      optimalRhMinPct: 85,
      optimalRhMaxPct: 90,
      typicalShelfLifeDays: 60,
      ethyleneProduction: 'VERY_LOW',
      keyDeteriorationFactors: 'Light greening (toxic glycoalkaloids), sprouting above 10°C, bacterial soft rot if moist.',
      packagingRequirements: 'Breathable light-blocking multiwall paper sacks, woven polypropylene (Leno mesh) bags; zero hermetic sealing.'
    }
  },
  {
    id: 3,
    name: 'Apple',
    slug: 'apple',
    category: 'Fresh Produce',
    perishability: 'MEDIUM',
    description: 'Pome fruit with moderate respiration and notable ethylene sensitivity. Prone to skin scuffing and impact bruising.',
    sampleImageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=800&auto=format&fit=crop&q=80',
    properties: {
      commodityId: 3,
      typicalPhMin: 3.3,
      typicalPhMax: 4.0,
      moistureContentPct: 84.0,
      moistureSensitivity: 'MODERATE',
      respirationRate: 'MODERATE',
      mechanicalSensitivity: 'MODERATE',
      chillingSensitivity: false,
      optimalTempMinC: 0.0,
      optimalTempMaxC: 4.0,
      optimalRhMinPct: 90,
      optimalRhMaxPct: 95,
      typicalShelfLifeDays: 30,
      ethyleneProduction: 'HIGH',
      keyDeteriorationFactors: 'Impact bruising, dehydration shrivel, internal browning from carbon dioxide buildup.',
      packagingRequirements: 'Cell-pack telescopic corrugated containers, molded fiber partition trays, micro-perforated liners.'
    }
  },
  {
    id: 4,
    name: 'Banana',
    slug: 'banana',
    category: 'Fresh Produce',
    perishability: 'HIGH',
    description: 'Tropical climacteric fruit with extreme susceptibility to chilling injury below 13°C and rapid ripening triggered by ethylene.',
    sampleImageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&auto=format&fit=crop&q=80',
    properties: {
      commodityId: 4,
      typicalPhMin: 4.5,
      typicalPhMax: 5.2,
      moistureContentPct: 75.0,
      moistureSensitivity: 'HIGH',
      respirationRate: 'HIGH',
      mechanicalSensitivity: 'VERY_HIGH',
      chillingSensitivity: true,
      optimalTempMinC: 13.0,
      optimalTempMaxC: 14.5,
      optimalRhMinPct: 90,
      optimalRhMaxPct: 95,
      typicalShelfLifeDays: 7,
      ethyleneProduction: 'HIGH',
      keyDeteriorationFactors: 'Peel scuffing, crown rot, rapid senescent spots, irreversible chilling injury (blackening).',
      packagingRequirements: 'Heavy-duty telescopic kraft corrugated boxes, polyethylene modified-atmosphere liners with ethylene scavengers.'
    }
  },
  {
    id: 5,
    name: 'Mango',
    slug: 'mango',
    category: 'Fresh Produce',
    perishability: 'HIGH',
    description: 'Stone fruit known as the King of Fruits. High moisture transpiration, rapid sugar conversion, and susceptibility to anthracnose.',
    sampleImageUrl: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&auto=format&fit=crop&q=80',
    properties: {
      commodityId: 5,
      typicalPhMin: 3.8,
      typicalPhMax: 4.5,
      moistureContentPct: 83.0,
      moistureSensitivity: 'HIGH',
      respirationRate: 'HIGH',
      mechanicalSensitivity: 'HIGH',
      chillingSensitivity: true,
      optimalTempMinC: 11.0,
      optimalTempMaxC: 13.0,
      optimalRhMinPct: 85,
      optimalRhMaxPct: 90,
      typicalShelfLifeDays: 12,
      ethyleneProduction: 'HIGH',
      keyDeteriorationFactors: 'Stem-end rot, fruit fly puncture, mechanical skin tear, sapburn.',
      packagingRequirements: 'Individual foam protective net sleeves, partitioned 5-ply corrugated CFB boxes with ventilation eyelets.'
    }
  },
  {
    id: 6,
    name: 'Onion',
    slug: 'onion',
    category: 'Bulb Vegetables',
    perishability: 'LOW',
    description: 'Tunicated bulb crop requiring strictly dry, high-airflow conditions to prevent root regeneration, mold, and neck rot.',
    sampleImageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800&auto=format&fit=crop&q=80',
    properties: {
      commodityId: 6,
      typicalPhMin: 5.3,
      typicalPhMax: 5.8,
      moistureContentPct: 86.0,
      moistureSensitivity: 'CRITICAL',
      respirationRate: 'VERY_LOW',
      mechanicalSensitivity: 'LOW',
      chillingSensitivity: false,
      optimalTempMinC: 0.0,
      optimalTempMaxC: 4.0,
      optimalRhMinPct: 65,
      optimalRhMaxPct: 70,
      typicalShelfLifeDays: 90,
      ethyleneProduction: 'VERY_LOW',
      keyDeteriorationFactors: 'Sprouting from humidity > 70%, bacterial soft rot, neck rot (Botrytis allii).',
      packagingRequirements: 'Maximum airflow open-mesh polypropylene leno bags, woven jute bags; never place in sealed plastic films.'
    }
  },
  {
    id: 7,
    name: 'Leafy Vegetables',
    slug: 'leafy-vegetables',
    category: 'Fresh Produce',
    perishability: 'ULTRA_HIGH',
    description: 'Spinach, fenugreek, coriander, mint. Extreme surface-area-to-volume ratio causes hyper-fast moisture evaporation and wilting.',
    sampleImageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800&auto=format&fit=crop&q=80',
    properties: {
      commodityId: 7,
      typicalPhMin: 5.5,
      typicalPhMax: 6.8,
      moistureContentPct: 92.0,
      moistureSensitivity: 'CRITICAL',
      respirationRate: 'EXTREMELY_HIGH',
      mechanicalSensitivity: 'VERY_HIGH',
      chillingSensitivity: false,
      optimalTempMinC: 0.0,
      optimalTempMaxC: 2.0,
      optimalRhMinPct: 95,
      optimalRhMaxPct: 98,
      typicalShelfLifeDays: 4,
      ethyleneProduction: 'LOW',
      keyDeteriorationFactors: 'Wilting within hours under ambient air, chlorophyll degradation (yellowing), bacterial liquefaction.',
      packagingRequirements: 'Perforated LDPE bags with moisture balance, MAP rigid trays with controlled gas transmission, cold top-icing.'
    }
  },
  {
    id: 8,
    name: 'Milk',
    slug: 'milk',
    category: 'Dairy Products',
    perishability: 'ULTRA_HIGH',
    description: 'Liquid emulsion of fat globules and proteins in water. High microbial spoilage risk, photolytic riboflavin degradation, strictly cold-chain.',
    sampleImageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&auto=format&fit=crop&q=80',
    properties: {
      commodityId: 8,
      typicalPhMin: 6.5,
      typicalPhMax: 6.7,
      moistureContentPct: 87.5,
      moistureSensitivity: 'CRITICAL',
      respirationRate: 'VERY_LOW',
      mechanicalSensitivity: 'HIGH',
      chillingSensitivity: false,
      optimalTempMinC: 2.0,
      optimalTempMaxC: 4.0,
      optimalRhMinPct: 70,
      optimalRhMaxPct: 80,
      typicalShelfLifeDays: 5,
      ethyleneProduction: 'VERY_LOW',
      keyDeteriorationFactors: 'Lactic acid bacterial multiplication, curdling, oxidation off-flavors caused by ambient light.',
      packagingRequirements: 'Liquid-tight aseptic multi-layer cartons (Tetra Pak), co-extruded UV-blocking multi-layer poly pouches, or sterilized PET/glass bottles.'
    }
  },
  {
    id: 9,
    name: 'Bread',
    slug: 'bread',
    category: 'Bakery Products',
    perishability: 'HIGH',
    description: 'Porous baked wheat flour matrix. Susceptible to starch retrogradation (staling), crust softening in high humidity, and mold growth.',
    sampleImageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
    properties: {
      commodityId: 9,
      typicalPhMin: 5.0,
      typicalPhMax: 5.8,
      moistureContentPct: 38.0,
      moistureSensitivity: 'HIGH',
      respirationRate: 'LOW',
      mechanicalSensitivity: 'HIGH',
      chillingSensitivity: false,
      optimalTempMinC: 18.0,
      optimalTempMaxC: 24.0,
      optimalRhMinPct: 50,
      optimalRhMaxPct: 60,
      typicalShelfLifeDays: 5,
      ethyleneProduction: 'VERY_LOW',
      keyDeteriorationFactors: 'Mold growth (Rhizopus stolonifer), retrogradation (crumb hardening accelerated by refrigeration), crust sogginess.',
      packagingRequirements: 'Micro-perforated polypropylene (BOPP) or low-density polyethylene bags with twist-tie closures; keep ambient, do not freeze/refrigerate.'
    }
  },
  {
    id: 10,
    name: 'Biscuits',
    slug: 'biscuits',
    category: 'Dry Packaged Food',
    perishability: 'LOW',
    description: 'Crisp, low-water baked confection (moisture 2-4%). Highly hygroscopic; rapidly loses crunch upon humidity exposure; fat oxidation.',
    sampleImageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&auto=format&fit=crop&q=80',
    properties: {
      commodityId: 10,
      typicalPhMin: 6.0,
      typicalPhMax: 7.0,
      moistureContentPct: 3.0,
      moistureSensitivity: 'CRITICAL',
      respirationRate: 'VERY_LOW',
      mechanicalSensitivity: 'VERY_HIGH',
      chillingSensitivity: false,
      optimalTempMinC: 15.0,
      optimalTempMaxC: 25.0,
      optimalRhMinPct: 30,
      optimalRhMaxPct: 45,
      typicalShelfLifeDays: 180,
      ethyleneProduction: 'VERY_LOW',
      keyDeteriorationFactors: 'Moisture ingress causing sogginess, physical crumbling from vibration, rancidity from oxygen exposure.',
      packagingRequirements: 'Metallized barrier film (BOPP / Met-PET laminate) pillow pouches, inner corrugated fluted sleeves, rigid master cartons.'
    }
  },
  {
    id: 11,
    name: 'Rice',
    slug: 'rice',
    category: 'Grains & Pulses',
    perishability: 'LOW',
    description: 'Hulled or polished cereal grain. Stable at low equilibrium moisture (12-14%), but highly prone to moisture absorption, weevils, and mold.',
    sampleImageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80',
    properties: {
      commodityId: 11,
      typicalPhMin: 6.0,
      typicalPhMax: 6.8,
      moistureContentPct: 12.0,
      moistureSensitivity: 'HIGH',
      respirationRate: 'VERY_LOW',
      mechanicalSensitivity: 'LOW',
      chillingSensitivity: false,
      optimalTempMinC: 15.0,
      optimalTempMaxC: 22.0,
      optimalRhMinPct: 50,
      optimalRhMaxPct: 65,
      typicalShelfLifeDays: 365,
      ethyleneProduction: 'VERY_LOW',
      keyDeteriorationFactors: 'Rice weevil (Sitophilus oryzae) infestation, mold growth and yellowing if relative humidity exceeds 70%.',
      packagingRequirements: 'High-density woven polypropylene (WPP) sacks with BOPP laminate, multiwall kraft bags, or vacuum-sealed bricks for premium aroma.'
    }
  },
  {
    id: 12,
    name: 'Wheat',
    slug: 'wheat',
    category: 'Grains & Pulses',
    perishability: 'LOW',
    description: 'Major food staple grain. Resilient during transport, but hygroscopic dampness triggers mold mycotoxins (aflatoxins) and pest infestation.',
    sampleImageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&auto=format&fit=crop&q=80',
    properties: {
      commodityId: 12,
      typicalPhMin: 6.0,
      typicalPhMax: 6.5,
      moistureContentPct: 11.5,
      moistureSensitivity: 'HIGH',
      respirationRate: 'VERY_LOW',
      mechanicalSensitivity: 'LOW',
      chillingSensitivity: false,
      optimalTempMinC: 15.0,
      optimalTempMaxC: 22.0,
      optimalRhMinPct: 50,
      optimalRhMaxPct: 65,
      typicalShelfLifeDays: 365,
      ethyleneProduction: 'VERY_LOW',
      keyDeteriorationFactors: 'Moisture condensation, grain heating from fungal growth, insect damage.',
      packagingRequirements: 'Breathable laminated woven polypropylene bags, heavy-gauge jute sacks, hermetic grain storage bags.'
    }
  }
];

export const PACKAGING_MATERIALS: PackagingMaterial[] = [
  {
    id: 1,
    name: 'Corrugated Fiberboard',
    slug: 'corrugated-fiberboard',
    category: 'Paper & Board',
    moistureBarrierRating: 45,
    oxygenBarrierRating: 20,
    mechanicalProtectionRating: 90,
    thermalInsulationRating: 68,
    minTempC: -15.0,
    maxTempC: 50.0,
    estimatedCostInrPerUnit: 18.50,
    recyclabilityRating: 95,
    biodegradabilityRating: 88,
    sustainabilityScore: 92,
    foodGradeCertified: true,
    compatibleCategories: ['Fresh Produce', 'Bakery Products', 'Dry Packaged Food', 'Grains & Pulses'],
    primaryAdvantages: 'Outstanding compressive stacking strength, superior shock cushioning during rough road transit, fully biodegradable and circular recycling.',
    primaryLimitations: 'Weak against direct standing water or extreme humidity (>85% RH) without specialized water-resistant barrier coatings.',
    specifications: '3-ply or 5-ply fluted kraft paperboard (B/C flute combination), burst factor 18-24 kg/cm².'
  },
  {
    id: 2,
    name: 'Plastic Tray (PET/RPET)',
    slug: 'plastic-tray',
    category: 'Rigid Plastic',
    moistureBarrierRating: 80,
    oxygenBarrierRating: 65,
    mechanicalProtectionRating: 78,
    thermalInsulationRating: 30,
    minTempC: -20.0,
    maxTempC: 60.0,
    estimatedCostInrPerUnit: 12.00,
    recyclabilityRating: 82,
    biodegradabilityRating: 10,
    sustainabilityScore: 55,
    foodGradeCertified: true,
    compatibleCategories: ['Fresh Produce', 'Bakery Products'],
    primaryAdvantages: 'High optical transparency for consumer inspection, anti-crush rigid side walls, stackable nested design.',
    primaryLimitations: 'Non-biodegradable; requires municipal closed-loop sorting stream for high circularity.',
    specifications: 'Thermoformed 350-500 micron food-contact RPET with punch ventilation slots.'
  },
  {
    id: 3,
    name: 'Polyethylene Terephthalate (PET)',
    slug: 'pet',
    category: 'Rigid Plastic',
    moistureBarrierRating: 88,
    oxygenBarrierRating: 76,
    mechanicalProtectionRating: 82,
    thermalInsulationRating: 35,
    minTempC: -20.0,
    maxTempC: 65.0,
    estimatedCostInrPerUnit: 14.50,
    recyclabilityRating: 88,
    biodegradabilityRating: 5,
    sustainabilityScore: 58,
    foodGradeCertified: true,
    compatibleCategories: ['Dairy Products', 'Beverages', 'Dry Packaged Food'],
    primaryAdvantages: 'High tensile strength, good aroma retention, shatter-resistant alternative to glass, lightweight transport emissions.',
    primaryLimitations: 'Lower temperature limit (deforms above 65°C); single-use plastic regulatory policies.',
    specifications: 'Biaxially oriented bottle or jar grade PET, density 1.38 g/cm³, OTR 50 cc/m²/day.'
  },
  {
    id: 4,
    name: 'High-Density Polyethylene (HDPE)',
    slug: 'hdpe',
    category: 'Rigid/Flexible Plastic',
    moistureBarrierRating: 92,
    oxygenBarrierRating: 40,
    mechanicalProtectionRating: 85,
    thermalInsulationRating: 45,
    minTempC: -40.0,
    maxTempC: 80.0,
    estimatedCostInrPerUnit: 9.80,
    recyclabilityRating: 85,
    biodegradabilityRating: 10,
    sustainabilityScore: 60,
    foodGradeCertified: true,
    compatibleCategories: ['Dairy Products', 'Fresh Produce', 'Grains & Pulses'],
    primaryAdvantages: 'Exceptional moisture vapor barrier, high chemical inertness, high stiffness-to-weight ratio, reusable crate applications.',
    primaryLimitations: 'Moderate oxygen barrier; translucent rather than crystal transparent.',
    specifications: 'Extruded blow-molded bottles or injection-molded crates, density 0.95 g/cm³, WVTR 3-5 g/m²/day.'
  },
  {
    id: 5,
    name: 'Low-Density Polyethylene (LDPE)',
    slug: 'ldpe',
    category: 'Flexible Film',
    moistureBarrierRating: 84,
    oxygenBarrierRating: 25,
    mechanicalProtectionRating: 45,
    thermalInsulationRating: 20,
    minTempC: -50.0,
    maxTempC: 65.0,
    estimatedCostInrPerUnit: 4.20,
    recyclabilityRating: 75,
    biodegradabilityRating: 10,
    sustainabilityScore: 52,
    foodGradeCertified: true,
    compatibleCategories: ['Fresh Produce', 'Bakery Products', 'Grains & Pulses'],
    primaryAdvantages: 'Very cost-effective, high flexibility, excellent heat sealing, reliable water/moisture protection.',
    primaryLimitations: 'Low oxygen barrier (high gas transmission), susceptible to puncture under sharp pressure.',
    specifications: 'Blown film 25-75 microns thickness, WVTR 15-20 g/m²/day, OTR > 2500 cc/m²/day.'
  },
  {
    id: 6,
    name: 'Polypropylene (PP)',
    slug: 'pp',
    category: 'Rigid/Woven Plastic',
    moistureBarrierRating: 90,
    oxygenBarrierRating: 48,
    mechanicalProtectionRating: 86,
    thermalInsulationRating: 50,
    minTempC: -10.0,
    maxTempC: 105.0,
    estimatedCostInrPerUnit: 8.50,
    recyclabilityRating: 80,
    biodegradabilityRating: 10,
    sustainabilityScore: 58,
    foodGradeCertified: true,
    compatibleCategories: ['Fresh Produce', 'Dry Packaged Food', 'Grains & Pulses', 'Root Vegetables'],
    primaryAdvantages: 'High thermal ceiling (withstands hot filling), outstanding flex fatigue endurance, woven breathable mesh bags (Leno bags) prevent sweating.',
    primaryLimitations: 'Brittle below sub-zero freezing temperatures without copolymer modification.',
    specifications: 'Woven monofilament mesh or solid molded containers, melting point 160°C.'
  },
  {
    id: 7,
    name: 'Glass Container',
    slug: 'glass',
    category: 'Rigid Glass',
    moistureBarrierRating: 100,
    oxygenBarrierRating: 100,
    mechanicalProtectionRating: 68,
    thermalInsulationRating: 40,
    minTempC: -30.0,
    maxTempC: 180.0,
    estimatedCostInrPerUnit: 28.00,
    recyclabilityRating: 98,
    biodegradabilityRating: 0,
    sustainabilityScore: 72,
    foodGradeCertified: true,
    compatibleCategories: ['Dairy Products', 'Preserved Foods', 'Beverages'],
    primaryAdvantages: '100% impermeable absolute barrier to moisture, oxygen, aromas, and pests. Non-leaching chemical inertness. Infinitely recyclable.',
    primaryLimitations: 'Heavy tare weight increases transit fuel consumption, brittle and fragile to drop impacts.',
    specifications: 'Type III soda-lime silicate glass, thermal shock resistance delta 42°C.'
  },
  {
    id: 8,
    name: 'Aluminum Foil / Barrier Laminate',
    slug: 'aluminum',
    category: 'Metal / Flexible Laminate',
    moistureBarrierRating: 100,
    oxygenBarrierRating: 100,
    mechanicalProtectionRating: 75,
    thermalInsulationRating: 55,
    minTempC: -40.0,
    maxTempC: 120.0,
    estimatedCostInrPerUnit: 22.00,
    recyclabilityRating: 90,
    biodegradabilityRating: 0,
    sustainabilityScore: 68,
    foodGradeCertified: true,
    compatibleCategories: ['Dry Packaged Food', 'Dairy Products', 'Beverages'],
    primaryAdvantages: 'Total light, oxygen, moisture, and microbial blackout barrier. Extends ambient shelf life for months.',
    primaryLimitations: 'Crease flex pinholing if crumpled severely; high energy intensity during raw bauxite extraction.',
    specifications: 'Tri-laminate PET/Alu/PE (12µm / 7µm / 50µm), WVTR < 0.01 g/m²/day.'
  },
  {
    id: 9,
    name: 'Paperboard / Folding Carton',
    slug: 'paperboard',
    category: 'Paper & Board',
    moistureBarrierRating: 50,
    oxygenBarrierRating: 25,
    mechanicalProtectionRating: 65,
    thermalInsulationRating: 45,
    minTempC: -10.0,
    maxTempC: 70.0,
    estimatedCostInrPerUnit: 7.50,
    recyclabilityRating: 92,
    biodegradabilityRating: 90,
    sustainabilityScore: 90,
    foodGradeCertified: true,
    compatibleCategories: ['Bakery Products', 'Dry Packaged Food'],
    primaryAdvantages: '100% renewable wood fiber base, compostable, space-saving flat shipment before erection, excellent brand printability.',
    primaryLimitations: 'Quickly loses rigidity when wet unless barrier-coated; moderate stacking weight capacity.',
    specifications: 'Solid Bleached Sulfate (SBS) virgin pulp board 280-350 gsm, food-grade barrier coating.'
  },
  {
    id: 10,
    name: 'Compostable Packaging (PLA/PBAT)',
    slug: 'compostable-packaging',
    category: 'Bio-based Plastic',
    moistureBarrierRating: 72,
    oxygenBarrierRating: 58,
    mechanicalProtectionRating: 68,
    thermalInsulationRating: 35,
    minTempC: -10.0,
    maxTempC: 45.0,
    estimatedCostInrPerUnit: 24.00,
    recyclabilityRating: 40,
    biodegradabilityRating: 98,
    sustainabilityScore: 88,
    foodGradeCertified: true,
    compatibleCategories: ['Fresh Produce', 'Bakery Products', 'Dry Packaged Food'],
    primaryAdvantages: 'Certified industrially compostable (EN 13432/ASTM D6400), derived from renewable cornstarch/sugarcane, zero microplastic persistence.',
    primaryLimitations: 'Softens above 45°C in hot summer transit; higher per-unit acquisition cost.',
    specifications: 'Bio-polymer film blend PLA/PBAT 30-50 microns thickness, bio-based carbon content > 80%.'
  },
  {
    id: 11,
    name: 'Modified Atmosphere Packaging (MAP)',
    slug: 'map',
    category: 'Specialized Barrier System',
    moistureBarrierRating: 94,
    oxygenBarrierRating: 90,
    mechanicalProtectionRating: 82,
    thermalInsulationRating: 50,
    minTempC: -15.0,
    maxTempC: 50.0,
    estimatedCostInrPerUnit: 26.50,
    recyclabilityRating: 60,
    biodegradabilityRating: 20,
    sustainabilityScore: 62,
    foodGradeCertified: true,
    compatibleCategories: ['Fresh Produce', 'Dairy Products', 'Bakery Products'],
    primaryAdvantages: 'Controlled headspace gas mixtures (elevated CO2/N2, suppressed O2) retard respiration and double or triple active shelf life.',
    primaryLimitations: 'Requires gas flushing equipment; accidental film puncture breaks protective equilibrium.',
    specifications: 'EVOH high-barrier multi-layer tray with peelable anti-fog heat seal lidding film.'
  },
  {
    id: 12,
    name: 'Vacuum Packaging',
    slug: 'vacuum-packaging',
    category: 'Specialized Barrier System',
    moistureBarrierRating: 96,
    oxygenBarrierRating: 96,
    mechanicalProtectionRating: 72,
    thermalInsulationRating: 35,
    minTempC: -25.0,
    maxTempC: 60.0,
    estimatedCostInrPerUnit: 19.00,
    recyclabilityRating: 65,
    biodegradabilityRating: 15,
    sustainabilityScore: 64,
    foodGradeCertified: true,
    compatibleCategories: ['Dry Packaged Food', 'Grains & Pulses'],
    primaryAdvantages: 'Complete evacuation of atmospheric oxygen prevents aerobic bacterial growth, mold, and insect reproduction.',
    primaryLimitations: 'Atmospheric collapse pressure crushes tender soft fruits (tomatoes, strawberries) and leafy greens.',
    specifications: 'Coextruded PA/PE multi-layer vacuum pouches (20µm Polyamide / 70µm Polyethylene).'
  }
];

export const CITY_COORDINATES_MAP: Record<string, { lat: number; lon: number; state: string; defaultTempC: number; defaultRh: number }> = {
  'mumbai': { lat: 19.0760, lon: 72.8777, state: 'Maharashtra', defaultTempC: 28.5, defaultRh: 76 },
  'pune': { lat: 18.5204, lon: 73.8567, state: 'Maharashtra', defaultTempC: 25.2, defaultRh: 62 },
  'delhi': { lat: 28.6139, lon: 77.2090, state: 'Delhi', defaultTempC: 31.0, defaultRh: 54 },
  'bengaluru': { lat: 12.9716, lon: 77.5946, state: 'Karnataka', defaultTempC: 23.4, defaultRh: 68 },
  'bangalore': { lat: 12.9716, lon: 77.5946, state: 'Karnataka', defaultTempC: 23.4, defaultRh: 68 },
  'hyderabad': { lat: 17.3850, lon: 78.4867, state: 'Telangana', defaultTempC: 29.0, defaultRh: 58 },
  'chennai': { lat: 13.0827, lon: 80.2707, state: 'Tamil Nadu', defaultTempC: 30.2, defaultRh: 78 },
  'kolkata': { lat: 22.5726, lon: 88.3639, state: 'West Bengal', defaultTempC: 29.8, defaultRh: 80 },
  'ahmedabad': { lat: 23.0225, lon: 72.5714, state: 'Gujarat', defaultTempC: 32.5, defaultRh: 50 },
  'nashik': { lat: 19.9975, lon: 73.7898, state: 'Maharashtra', defaultTempC: 24.8, defaultRh: 65 },
  'nagpur': { lat: 21.1458, lon: 79.0882, state: 'Maharashtra', defaultTempC: 30.5, defaultRh: 55 },
  'jaipur': { lat: 26.9124, lon: 75.7873, state: 'Rajasthan', defaultTempC: 31.2, defaultRh: 45 },
  'lucknow': { lat: 26.8467, lon: 80.9462, state: 'Uttar Pradesh', defaultTempC: 28.0, defaultRh: 60 },
  'chandigarh': { lat: 30.7333, lon: 76.7794, state: 'Punjab/Haryana', defaultTempC: 26.5, defaultRh: 58 },
  'surat': { lat: 21.1702, lon: 72.8311, state: 'Gujarat', defaultTempC: 29.5, defaultRh: 72 },
  'indore': { lat: 22.7196, lon: 75.8577, state: 'Madhya Pradesh', defaultTempC: 27.8, defaultRh: 56 },
  'shimla': { lat: 31.1048, lon: 77.1734, state: 'Himachal Pradesh', defaultTempC: 14.5, defaultRh: 65 }
};
